#!/bin/bash
ARCH=$1
RELEASE=$2
URLBASE="https://github.com/pi-hole/FTL/releases/download/$RELEASE"
echo "Update FTL to $ARCH-$RELEASE"
case $ARCH in
	arm)
		URL="$URLBASE/pihole-FTL-armv7-linux-gnueabihf"
	;;
	arm64)
		URL="$URLBASE/pihole-FTL-aarch64-linux-gnu"
	;;
	amd64) 
		URL="$URLBASE/pihole-FTL-linux-x86_64"
        ;;
esac
echo "URL $URL"

curl -sLo /usr/bin/pihole-FTL "$URL"
chmod 755 /usr/bin/pihole-FTL
